/** Country-level `contact_location` values accepted by code_crafter/leads-finder. */
export const LEADS_FINDER_WORLDWIDE_COUNTRIES = [
  "united states",
  "germany",
  "india",
  "united kingdom",
  "russia",
  "france",
  "china",
  "canada",
  "netherlands",
  "mexico",
  "belgium",
  "japan",
  "brazil",
  "australia",
  "poland",
  "thailand",
  "sweden",
  "portugal",
  "spain",
  "czech republic",
  "taiwan",
  "south africa",
  "colombia",
  "italy",
  "vietnam",
  "nigeria",
  "singapore",
  "hong kong",
  "ireland",
  "israel",
  "switzerland",
  "turkey",
  "romania",
  "south korea",
  "indonesia",
  "united arab emirates",
  "saudi arabia",
  "austria",
  "philippines",
  "peru",
  "malaysia",
  "argentina",
  "ukraine",
  "ghana",
  "denmark",
  "norway",
  "finland",
  "puerto rico",
  "qatar",
  "macau",
  "new zealand",
  "hungary",
  "luxembourg",
  "kuwait",
  "egypt",
  "slovakia",
  "greece",
  "kenya",
  "bulgaria",
  "costa rica",
  "chile",
  "venezuela",
  "afghanistan",
  "bangladesh",
  "malta",
  "guatemala",
  "pakistan",
  "lithuania",
  "panama",
  "morocco",
  "republic of indonesia",
  "uruguay",
  "serbia",
  "bolivia",
  "angola",
  "dominican republic",
  "ecuador",
  "oman",
  "jamaica",
  "zambia",
  "lebanon",
  "tanzania",
  "jordan",
  "algeria",
  "gibraltar",
  "paraguay",
  "cambodia",
  "uganda",
  "mozambique",
  "ethiopia",
  "belarus",
  "republic of the union of myanmar",
  "croatia",
  "jersey",
  "iraq",
  "isle of man",
  "el salvador",
  "estonia",
  "latvia",
  "côte d'ivoire",
  "tunisia",
  "sierra leone",
  "senegal",
  "sri lanka",
  "cyprus",
  "kazakhstan",
  "guernsey",
  "bermuda",
  "mali",
  "honduras",
  "bahrain",
  "slovenia",
  "papua new guinea",
  "iceland",
  "mauritius",
  "iran",
  "niger",
  "rwanda",
  "moldova",
  "democratic republic of the congo",
  "liechtenstein",
  "fiji",
  "kyrgyzstan",
  "azerbaijan",
  "madagascar",
  "trinidad and tobago",
  "lesotho",
  "nicaragua",
  "cameroon",
  "barbados",
  "armenia",
  "haiti",
  "maldives",
  "guam",
  "laos",
  "nepal",
  "brunei",
  "reunion",
  "macedonia (fyrom)",
  "swaziland",
  "liberia",
  "uzbekistan",
  "sudan",
  "anguilla",
  "cuba",
  "cayman islands",
  "seychelles",
  "saint kitts and nevis",
  "suriname",
  "bosnia and herzegovina",
  "malawi",
  "the bahamas",
  "botswana",
  "syria",
  "burundi",
  "guadeloupe",
  "namibia",
  "burkina faso",
  "somalia",
  "greenland",
  "equatorial guinea",
  "chad",
  "monaco",
  "republic of the congo",
  "u.s. virgin islands",
  "mayotte",
  "french polynesia",
  "french guiana",
  "andorra",
  "new caledonia",
  "central african republic",
  "myanmar (burma)",
  "belize",
  "aland islands",
  "solomon islands",
  "kosovo",
  "gabon",
  "benin",
  "bonaire, sint eustatius and saba",
  "martinique",
  "tonga",
  "south sudan",
  "cook islands",
  "georgia",
  "mauritania",
  "turkmenistan",
  "libya",
  "falkland islands (islas malvinas)",
  "bhutan",
  "tajikistan",
  "northern mariana islands",
  "western sahara",
  "guyana",
  "dominica",
  "vanuatu",
  "kiribati",
  "togo",
  "nauru",
  "samoa",
  "mongolia",
  "myanmar",
  "yemen",
  "albania",
  "montenegro"
] as const
